{"uuid": "1dcf50a0-75b6-4437-aec2-8acc3851bf8e", "befores": [{"name": "common_driver", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"C:\\python3.8\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\study\\pythonT\\pyAppium-master\\testcase\\conftest.py\", line 32, in common_driver\n    driver = base_driver.base_driver()\n  File \"C:\\study\\pythonT\\pyAppium-master\\common\\base_driver.py\", line 40, in base_driver\n    desired_caps['appActivity'] = get_app_launchable_activity()\n  File \"C:\\study\\pythonT\\pyAppium-master\\common\\app_info.py\", line 39, in get_app_launchable_activity\n    launchable_activity = result.strip().split(\" \")[2].split('=')[1].replace(\"label\", '')\n"}, "start": 1697640867782, "stop": 1697640868266}], "start": 1697640867782, "stop": 1697640868732}