{"name": "test_login", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "cmdopt = \"{'platform_version': '7.1.2', 'server_port': 4723, 'system_port': 8200, 'device': '127.0.0.1:62001'}\"\n\n    @pytest.fixture(scope='session')\n    def common_driver(cmdopt):\n        global driver\n        base_driver = BaseDriver(eval(cmdopt))\n>       driver = base_driver.base_driver()\n\ntestcase\\conftest.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\base_driver.py:40: in base_driver\n    desired_caps['appActivity'] = get_app_launchable_activity()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def get_app_launchable_activity() -> str:\n        cmd = \"aapt dump badging {} | findstr launchable\".format(os.path.join(appPath, get_app_name(appPath)))\n        result = exec_cmd(cmd)\n        if \"launchable\" in result:\n>           launchable_activity = result.strip().split(\" \")[2].split('=')[1].replace(\"label\", '')\nE           IndexError: list index out of range\n\ncommon\\app_info.py:39: IndexError"}, "description": "用户正常登录", "start": 1697639546563, "stop": 1697639546563, "uuid": "7dd41497-76ab-4b09-8813-ece9c03f8431", "historyId": "9cc6a15665939beaaa7487d2db8f76b8", "testCaseId": "9cc6a15665939beaaa7487d2db8f76b8", "fullName": "63_testcase.test_login.TestLogin#test_login", "labels": [{"name": "severity", "value": "blocker"}, {"name": "story", "value": "正常登录"}, {"name": "feature", "value": "登录"}, {"name": "parentSuite", "value": "63_testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-CHVCFJK"}, {"name": "thread", "value": "23352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "63_testcase.test_login"}]}